name: GitHub Actions Demo

run-name: ${{ github.actor }} is testing out GitHub Actions 🚀

on:
  push:
    branches:
    - main
    - dev
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install deps
        run: python -m pip install --upgrade pip
      - name: Test
        run: python test.py